[package]
name = "ftc_http"
version = "1.1.1"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]

[lib]
name = "ftc_http"
path = "src/lib.rs"

[[bin]]
name = "ftc_http"
path = "src/main.rs"

[dependencies]
reqwest = "0.*.*"
walkdir = "2.*.*"
