[package]
name = "ftc_http"
version = "2.0.0"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]
edition = "2018"

[dependencies]
clap ="*"
structopt = "*"

[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest.git"
default-features = false
features = ["blocking"]