[package]
name = "ftc_http"
version = "1.2.0"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]

[lib]
name = "ftc_http"
path = "src/lib.rs"

[[bin]]
name = "ftc_http"
path = "src/main.rs"

[dependencies]
hyper = "0.11"
walkdir = "2.*.*"
