[package]
name = "ftc_http"
version = "2.0.0"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]
edition = "2018"

[dependencies]
clap ="*"
structopt = "*"
walkdir = "*"

[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest.git"
default-features = false
features = ["blocking", "cookies", "gzip"]

[dependencies.confy]
git = "https://github.com/rust-cli/confy.git"

[dependencies.serde]
version = "*"
features = ["derive"]